name: campussocial
description: "A new Flutter project for a social network."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  
  # State Management
  provider: ^6.1.2
  
  # API & Utilities
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
